### ISSUE TITLE
Include library specific CSS file in /dist

### ISSUE THREAD

**Issue by mattboldt** [chrisssycollins/vanilla-calendar#1]
The `styles.css` file contains styles for the entire body and container of your demo page. It'd be nice if there was a CSS file stripped of all demo code and using class names for your plugin specifically in `/dist`.

**Comment by chrissy-dev** [comment]
@mattboldt Fixed in: [v0.0.1](https://github.com/chrisssycollins/vanilla-calendar/releases/tag/v0.0.1)
