### ISSUE TITLE
Let's create a backlog

### ISSUE THREAD

**Issue by alperklc** [chrisssycollins/vanilla-calendar#11]
It's exciting to see people collaborating here :)

I'm currently working on setting up the development environment and the structure of the component. Just created a pull request, affecting many parts in the project: https://github.com/chrisssycollins/vanilla-calendar/pull/10 

In order to avoid merge conflicts and double efforts, I am proposing to create a backlog here.

Alper

**Comment by chrissy-dev** [comment]
@alperklc Excellent! I'll have a look over your PR very soon. More than happy to use the Issues as a backlog. Create a new issue for each thing, small manageable deliverables.
