### ISSUE TITLE
Month beginning with a sunday

### ISSUE THREAD

**Issue by LarsKuizenga** [chrisssycollins/vanilla-calendar#5]
April this year starts with a sunday. The calendar apears skip this and go to monday instead. The following month doesn't start with a sunday but is also bumped forward a day probably because of this. Maybe someone who understands this code a quick fix for it?

**Comment by chrissy-dev** [comment]
@xXLars007Xx Intresting bug, fixed in [0.0.2](https://github.com/chrisssycollins/vanilla-calendar/releases/tag/v0.0.2)
